name: Build Android APK

     on: [push]

     jobs:
       build:
         runs-on: ubuntu-latest
         steps:
           - uses: actions/checkout@v2
           - name: Setup .NET
             uses: actions/setup-dotnet@v1
             with:
               dotnet-version: '8.0.x'
           - name: Restore dependencies
             run: dotnet restore
           - name: Build
             run: dotnet build --configuration Release
           - name: Publish APK
             run: dotnet publish -f:net8.0-android -c:Release
           - name: Upload APK
             uses: actions/upload-artifact@v2
             with:
               name: app-release.apk
               path: SeuProjeto/bin/Release/net8.0-android/com.seuapp.apk
